### ISSUE TITLE
Breaking changes of manifest v3(version 1.17.0)

### ISSUE THREAD

**Issue by brookhong** [brookhong/Surfingkeys#2159]
Hi All,

On September 16, 2024, 1.17.0 was released(only for Chrome now, from branch [mv3](https://github.com/brookhong/Surfingkeys/tree/mv3)) to address manifest v3 upgrade, otherwise the extension would be taken down from chrome web store.

For now, please turn on `Developer mode` from `chrome://extensions/` after you installed/upgraded to 1.17.0, due to following reason

    The 'userScripts' API is only available for users in developer mode.

See [offical docs from Google](https://developer.chrome.com/docs/extensions/reference/api/userScripts#developer_mode_for_extension_users).

Then restart your browser, most features should work. And here are some known issues

* `api.vmapkey` is missing.
* `api.Hints.setCharacter` is missing.
* `settings.blocklistPattern` is not working.
* `chrome.storage` is not allowed in setting snippets.

**Comment by lost22git** [comment]
> please turn on Developer mode

It's working fine for me, thanks.

**Comment by lcaturelli** [comment]
Enabling developer mode, manages to load and save settings from URL successfully.

However, settings fails to apply (extension works with the default configuration). In console it shows the following errors:

![image](https://github.com/user-attachments/assets/701bc98d-a851-4402-a0d6-da1c306d3966)

I confirm that, if enabled/disable "developer options", it is necessary to restart the Browser to apply the change.

Vivaldi 6.9.3447.37 (Stable channel) (32 bits).

I am available if I can help with tests.

**Comment by nekowasabi** [comment]
Same error by saving advanced mode setting.

![CleanShot 2024-09-19 at 09 30 46@2x](https://github.com/user-attachments/assets/9144f89e-4cdc-48ad-8e1d-675972a79ec6)

**Comment by LoinApex** [comment]
![image](https://github.com/user-attachments/assets/3d669b14-dc0f-4e03-898b-9303472b776f)


Trun on the dev model, it doesn't  seem to be working  , Can I try something else?

**Comment by kings2u** [comment]
Thank you for addressing this so quickly. FYI, this line in my config also causes an error:
```
chrome.storage.local.set({"noPdfViewer": 1})
```

**Comment by daanzu** [comment]
```[SurfingKeys] Error found in settings: TypeError: Hints.setNumeric is not a function```

**Comment by agguser** [comment]
```
Uncaught TypeError: api.Front.showBanner is not a function
```

**Comment by stanbrom** [comment]
Can anyone help me with this? It's so sad all my Advanced mode setting can't work. :-(
Chorme 129.0.6668.59 Surfingkeys 1.17.0
Refused to load the script 'chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/worker-javascript.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by wthueb** [comment]
For those of you with the know how, checkout commit f82181963 (1.16.1) and build it from source yourself, and load the unpacked extension. The APIs still work, the new update just had to remove them to not get removed from the Chrome Web Store.

This won't work forever as Manifest v2 will eventually be unsupported entirely, but for now it allows Surfingkeys to be usable on Chrome for me.

**Comment by Kiraalla** [comment]
When will it be updated to [version 1.17.1]

**Comment by desgua** [comment]
Can someone guide me on how to build from source?
I have done (in Linux terminal):

```
git clone https://github.com/brookhong/Surfingkeys.git
cd Surfingkeys
git checkout f82181963
```
Then I go to chrome://extensions/ but when I try to load unpacked I get an error "Failed to load extension
File
~/Downloads/surfingkeys/Surfingkeys/src
Error
Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536"

**Comment by psych3r** [comment]
@desgua You have to build the extension first.
Run the following commands in the extension directory:
```
npm install
browser=chrome npm run build:prod
```
Then load unpacked `dist/production/chrome`

**Comment by desgua** [comment]
@psych3r Thank you so much! <3

**Comment by snowman** [comment]
> For those of you with the know how, checkout commit https://github.com/brookhong/Surfingkeys/commit/f82181963aaa0cd5a2e0f68b0a5beab3f5b73c68 (1.16.1)

why there is not `git tag` for this...

**Comment by clarkwang** [comment]
As a workaround for `settings.blocklistPattern`, I use `api.unmapAllExcept([], url_pattern)` to unmap all keybindings for specific sites. For example:

```
api.unmapAllExcept([], /^https:\/\/(calendar|contacts|docs|drive|keep).google.com/);
```

**Comment by lpanebr** [comment]
> As a workaround for `settings.blocklistPattern`, I use `api.unmapAllExcept([], url_pattern)` to unmap all keybindings for specific sites. For example:
> 
> ```
> api.unmapAllExcept([], /^https:\/\/(calendar|contacts|docs|drive|keep).google.com/);
> ```

unfortunately this workaround is not working for me (developer mode enabled).

This is so sad...

**Comment by brookhong** [comment]
1.17.1 has been released, above mentioned issue should have been resolved.

**Comment by 404pilot** [comment]
> As a workaround for `settings.blocklistPattern`, I use `api.unmapAllExcept([], url_pattern)` to unmap all keybindings for specific sites. For example:
> 
> ```
> api.unmapAllExcept([], /^https:\/\/(calendar|contacts|docs|drive|keep).google.com/);
> ```

it seems it doesn't work with the new version `1.17.1`, now I am running out of both options

**Comment by lpanebr** [comment]
This is very unfortunate. I've tried other extension but it doesn't cut it.
I miss surfing the web.

**Comment by brookhong** [comment]
Closing this since all known issues from MV3 upgrade have been fixed now.

**Comment by agguser** [comment]
`Uncaught TypeError: api.insertJS is not a function`

**Comment by rosshadden** [comment]
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addListener')

```javascript
    chrome.runtime.onMessage.addListener((function(e, t, n) {
        i[e.subject] && i[e.subject](e, t, n)
    }
```

**Comment by pablospe** [comment]
Fixed it by replacing `chrome.storage.local.set({"noPdfViewer": 1});` with `settings.noPdfViewer=true;` in the config.

From this comment: [here](https://github.com/brookhong/Surfingkeys/issues/2156#issuecomment-2357808392)

**Comment by cibinmathew** [comment]
Does this still work `chrome.storage.local.get`? Even with latest version, I am getting it as undefined

> Closing this since all known issues from MV3 upgrade have been fixed now.
