### ISSUE TITLE
Only "Mouse Click", "Scroll Page / Element" and "Omnibar" functionality working

### ISSUE THREAD

**Issue by matko031** [brookhong/Surfingkeys#2149]
## Error details

SurfingKeys: 1.17.0

Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

URL: everywhere
## Context

I just installed surfingkeys in brave and most mappings don't seem to work. The mappings from groups  "Mouse Click", "Scroll Page / Element" and "Omnibar" are working ok, but all the others not. For instance switching tabs with E/R or choosing a tab with T has no effect whatsoever. I tried this in brave, chrome, and chromimum and in all three cases it's the same issue. In Firefox everything works fine.

**Comment by brookhong** [comment]
1.17.0 is released for MV3 upgrade, I works well in my Chrome 128.0.6613.138. Any errors from console(Inspect tool)?

**Comment by PhilStar101** [comment]
@brookhong  After todays update alt+s to toggle surfing keys stop working. Chrome 128.0.6613.138, no console errors or something

**Comment by matko031** [comment]
I also have 128.0.6613.138 chromium version and there are no errors in the console

**Comment by dmfay** [comment]
I noticed the extension settings seem no longer persistent -- the "advanced mode" checkbox and settings path both clear once I leave the page.

**Comment by rosshadden** [comment]
Starting today I get an error that `api.Hints.setCharacters` is not a function (on `1.17.0`).

**Comment by aka-phrankie** [comment]
I found that my custom configuration could not be saved, and the system's built-in button `X` to close the page could not be used. 

I would like to ask if this is a function that cannot be achieved by **manifest v3** or a bug.

**Comment by brookhong** [comment]
@rosshadden Yes, that function is missed, will be fixed soon. So you can load your config file, right?

**Comment by rosshadden** [comment]
Yeah I just commented out the line for now :+1:.

**Comment by desgua** [comment]
I can't change any settings nor can I load my old settings. I'm using Chrome 128.0.6613.137 (Official Build) (64-bit Linux) and SurfingKeys 1.17.0.

**Comment by desgua** [comment]
Is there a way to downgrade the extension?

**Comment by frankzvitale** [comment]
> @brookhong After todays update alt+s to toggle surfing keys stop working. 

Also here to report alt+s not working; previously toggled websites are now active and I cannot re-toggle anything. Passthrough mode continues to work as a temporary workaround

**Comment by desgua** [comment]
This is how the settings page is looking since the 1.17.0 update.
![screenshot_2024_09_16_16_04_23](https://github.com/user-attachments/assets/74dfdbc4-e2f2-4db9-ae11-ca68273ecec3)

**Comment by thiendiahui** [comment]
[SurfingKeys] Error found in settings: TypeError: api.Hints.setCharacters is not a function

**Comment by orangeMangoDimz** [comment]
Yes, I am facing many of the same issues, like the “OG” shortcut to search through google is also not working. Even my custom configuration in advance mode is also missing.

![image](https://github.com/user-attachments/assets/38e6ef1d-60a2-43a1-8540-c34f8f6e29e9)

**Comment by brookhong** [comment]
@desgua @orangeMangoDimz Is there any error from console(Inspect tool) for the options page?

**Comment by brookhong** [comment]
> [SurfingKeys] Error found in settings: TypeError: api.Hints.setCharacters is not a function

Known issue, will be fixed soon.

**Comment by TanukiLoop** [comment]
> ## Error details
> SurfingKeys: 1.17.0
> 
> Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
> 
> URL: everywhere
> 
> ## Context
> I just installed surfingkeys in brave and most mappings don't seem to work. The mappings from groups "Mouse Click", "Scroll Page / Element" and "Omnibar" are working ok, but all the others not. For instance switching tabs with E/R or choosing a tab with T has no effect whatsoever. I tried this in brave, chrome, and chromimum and in all three cases it's the same issue. In Firefox everything works fine.

Found my way here because of the same issue/experience. Was surprised that the previous/next tab keys stopped functioning as before despite running the default settings and seeing no errors in the console.

Thanks for the firefox reminder.

Browser: [Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by dmfay** [comment]
> @desgua @orangeMangoDimz Is there any error from console(Inspect tool) for the options page?

not on load but when I try to save the path to my script after ticking the advanced-user checkbox I get this:

```
options.js:1 Uncaught TypeError: Cannot read properties of null (reading 'getValue')
    at HTMLInputElement.A (options.js:1:3849)
```

this points to line 2 in this minified function:

```js
    function A() {
        var t = u.getValue()
          , o = E(w.value.trim());
        o.length && o !== x ? e("loadSettingsFromUrl", {
            url: o
        }, (function(e) {
            l(e.status + " to load settings from " + o, 5e3),
            K(e),
            e.snippets && e.snippets.length ? (x = o,
            u.setValue(e.snippets, -1)) : "" === t && u.setValue(P, -1)
        }
        )) : (e("updateSettings", {
            settings: {
                snippets: t,
                localPath: E(w.value)
            }
        }),
        l("Settings saved", 1e3))
    }
```

**Comment by orangeMangoDimz** [comment]
> @desgua @orangeMangoDimz Is there any error from console(Inspect tool) for the options page?

Nope

![image](https://github.com/user-attachments/assets/5099efeb-4af9-4520-a7a4-adeb5f653b01)

**Comment by brookhong** [comment]
Please go to `chrome://extensions/`, click on the link to `service worker`, then check if there is any error from the popup console.
<img width="407" alt="image" src="https://github.com/user-attachments/assets/7834b00b-8508-428b-a24c-6a19f6a38744">

**Comment by dmfay** [comment]
> Please go to `chrome://extensions/`, click on the link to `service worker`, then check if there is any error from the popup console. <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/288207/367990491-7834b00b-8508-428b-a24c-6a19f6a38744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDE5NDMsIm5iZiI6MTcyNjU0MTY0MywicGF0aCI6Ii8yODgyMDcvMzY3OTkwNDkxLTc4MzRiMDBiLTg1MDgtNDI4Yi1hMjRjLTZhMTlmNmEzODc0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwMjU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzc3NjM4ZjJiZmZhYzBhMzBiNzMwNmRhNDVmYjRlN2MzMjU3NTA0MzEwOGIyZWE0ODFmNzAyMzYxODRhYzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7R9IIJB-oHhCjLMWfpzPP7YUFPpkLXSJwk54iQ4me0g">

The service worker shows (inactive) and clicking the link doesn't do anything for me.

**Comment by j8s0n** [comment]
I'm experiencing this on one of my Arch machines running Brave. I like Brave, but I can't use a browser without SurfingKeys, so I might have to try Firefox.

**Comment by brookhong** [comment]
> > Please go to `chrome://extensions/`, click on the link to `service worker`, then check if there is any error from the popup console. <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/288207/367990491-7834b00b-8508-428b-a24c-6a19f6a38744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDE5NDMsIm5iZiI6MTcyNjU0MTY0MywicGF0aCI6Ii8yODgyMDcvMzY3OTkwNDkxLTc4MzRiMDBiLTg1MDgtNDI4Yi1hMjRjLTZhMTlmNmEzODc0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwMjU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzc3NjM4ZjJiZmZhYzBhMzBiNzMwNmRhNDVmYjRlN2MzMjU3NTA0MzEwOGIyZWE0ODFmNzAyMzYxODRhYzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7R9IIJB-oHhCjLMWfpzPP7YUFPpkLXSJwk54iQ4me0g">
> 
> The service worker shows (inactive) and clicking the link doesn't do anything for me. I'm using Vivaldi but it does support ManifestV3 afaik

That might be the problem. You can reload the extension and see if the link will be activated, then click the link to open the console and save your config file path to check the errors from the console.

**Comment by matko031** [comment]
> > Please go to `chrome://extensions/`, click on the link to `service worker`, then check if there is any error from the popup console. <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/288207/367990491-7834b00b-8508-428b-a24c-6a19f6a38744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDE5NDMsIm5iZiI6MTcyNjU0MTY0MywicGF0aCI6Ii8yODgyMDcvMzY3OTkwNDkxLTc4MzRiMDBiLTg1MDgtNDI4Yi1hMjRjLTZhMTlmNmEzODc0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwMjU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzc3NjM4ZjJiZmZhYzBhMzBiNzMwNmRhNDVmYjRlN2MzMjU3NTA0MzEwOGIyZWE0ODFmNzAyMzYxODRhYzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7R9IIJB-oHhCjLMWfpzPP7YUFPpkLXSJwk54iQ4me0g">
> 
> The service worker shows (inactive) and clicking the link doesn't do anything for me. I'm using Vivaldi but it does support ManifestV3 afaik

I had the same issue and after removing and re-adding the extension service worker is working as well as all the functionality

**Comment by matko031** [comment]
Just an additional clarification, I just installed the extension in another brave profile and it did not work again. I tried removing it and adding it and still nothing. For some reason, I have to click on `service worker (inactive)` (where nothing seems to happen) and then after removing and adding it again it works fine.

**Comment by brookhong** [comment]
Wow, thanks @matko031. Looks like there are some incompatible settings left from previous version, so a workable solution would be removing and adding the extension.
